#!/usr/bin/env bash
# Displays 'Best School'. Displays Hi on the 9th iteration

madut=0

while [ $madut -lt 10 ]
do
  if [ $madut -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( madut++ ))
done
