#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

list=$(ls)
for m in $list; do
  echo "$m" | cut -d '-' -f2
done
